replicaCount: 1
fullnameOverride: supplier-service
image:
  repository: lehardocker/supplier-service
  tag: sha-f4419bc
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8084
  targetPort: 8084
