replicaCount: 1

fullnameOverride: notification-service

image:
  repository: lehardocker/notification-service
  tag: v1.0.0
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000