replicaCount: 2
fullnameOverride: drug-catalog-service
image:
  repository: lehardocker/drug-catalog-service
  tag: v1.0.0
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082