replicaCount: 1
fullnameOverride: drug-catalog-service
image:
  repository: lehardocker/drug-catalog-service
  tag: sha-2a675a2
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8082
  targetPort: 8082
