replicaCount: 1
fullnameOverride: manufacturing-service
image:
  repository: lehardocker/manufacturing-service
  tag: sha-037d76a
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8085
  targetPort: 8085
