replicaCount: 1
fullnameOverride: inventory-service
image:
  repository: lehardocker/inventory-service
  tag: sha-a0017b8
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8083
  targetPort: 8083
